## Top 8 python tools for deeper data analysis

1. Groupby
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del(keyword)

### Groupby

In [1]:
import pandas as pd

In [2]:
insurance_data = pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### 1.1 initial analysis

In [3]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
insurance_data.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [5]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 1.2 pull up the average isurance charges based on region

In [6]:
insurance_data["region"].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [7]:
insurance_data.groupby("region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

In [8]:
insurance_data.groupby("region")["charges"].mean().round(2).sort_values(ascending=False)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [9]:
insurance_data.head(7)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960

### 1.3 pull up the average isurance charges based on "region and Sex"
* discrete - Countable/can't be segmented.
* Continuous - measurable/have units/can be segmented..

In [10]:
insurance_data.groupby(["region","sex"])["charges"].mean().round(2).sort_values(ascending=False)

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

## 2.pivot_Table

In [11]:
pd.pivot_table(data=insurance_data,values="charges",index="region",columns="sex") #Presentable comprriing 2 categorical features along with 
                                                                                #1 continuous data.

sex              female          male
region
northeast  12953.203151  13854.005374
northwest  12479.870397  12354.119575
southeast  13499.669243  15879.617173
southwest  11274.411264  13412.883576

In [12]:
pd.pivot_table(data=insurance_data,values="charges",index="region",columns=["sex","children"])

sex              female                                            \
children              0             1             2             3
region
northeast   9789.822330  17124.689856  14523.222213  13730.098756
northwest  12583.872074  11118.855757  13127.592952  13430.708082
southeast  14862.013008   9869.908240  11766.313671  19722.982900
southwest  10149.745507  10841.643945  16230.264372   8438.736294

sex                                           male                \
children              4            5             0             1
region
northeast  14542.416663          NaN  13389.637372  15474.289174
northwest  11024.418200   8965.79575   9812.969532   9515.042120
southeast  18267.100687   9923.88820  13791.806750  17424.652082
southwest  10945.677243  10023.64775  13727.264465   9971.325962

sex
children              2             3             4             5
region
northeast  12317.910591  14935.224532  14442.275463   6978.973483
northwest  13762.553939  22971.223279  11508.318988           NaN
southeast  18647.954693  17101.818726   8726.908900  10306.994883
southwest  18875.953545  12071.592329  17923.948000   6864.669500

## 3.Aggregate

### pull up the average isurance charges based on region to analyse max,min,sum

In [13]:
insurance_data.groupby("region")["charges"].agg(["mean","min","max","sum"]).round()

              mean     min      max        sum
region
northeast  13406.0  1695.0  58571.0  4343669.0
northwest  12418.0  1621.0  60021.0  4035712.0
southeast  14735.0  1122.0  63770.0  5363690.0
southwest  12347.0  1242.0  52591.0  4012755.0

In [14]:
insurance_data.groupby(["region","sex"])["charges"].agg(["mean","min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4.cross_tab

### how many smokers and non smokers based on regionwise
The frequencies of comparing two Caterical Features

In [15]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [16]:
pd.crosstab(index=insurance_data["region"],columns=insurance_data["smoker"])

smoker      no  yes
region
northeast  257   67
northwest  267   58
southeast  273   91
southwest  267   58

In [17]:
pd.crosstab(index=insurance_data["region"],columns=insurance_data["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

## 5. Concat

In [18]:
sales_data_2017 = pd.read_csv("Sales transaction 2017.csv")
sales_data_2018 = pd.read_csv("Sales transaction 2018.csv")
sales_data_2019 = pd.read_csv("Sales transaction 2019.csv")

In [19]:
sales_full_data = pd.concat([sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [20]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [21]:
sales_full_data.dtypes

Date              str
Voucher           str
Party             str
Product           str
Qty               str
Rate              str
Gross             str
Disc              str
Voucher Amount    str
dtype: object

In [22]:
sales_edited_data = pd.read_csv("Sales transaction .edited.csv")
sales_edited_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [23]:
sales_edited_data.dtypes

Date           str
Voucher      int64
Party          str
Product        str
Qty          int64
Rate       float64
dtype: object

### Task compexiy = 4.5/5:
Date  : str   convert  str into date time

### Task - merge function() explore - jeft join,right join,innerr join,outer join

In [24]:
insurance_data.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [25]:
insurance_data[["age","region"]]

      age     region
0      19  southwest
1      18  southeast
2      28  southeast
3      33  northwest
4      32  northwest
...   ...        ...
1333   50  northwest
1334   18  northeast
1335   18  southeast
1336   21  southwest
1337   61  northwest

[1338 rows x 2 columns]

## 6.Apply

### create a new column in the name data frame "Eligibility_criteria" where if age is > 25

In [26]:
def get_age(x):
    if x > 25:
        return "Eligible"
    else:
        return "Not Eligibble"

In [27]:
insurance_data["Eligible Criteria"] = insurance_data["age"].apply(get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibble
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibble
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibble
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibble
1336,21,female,25.800,0,no,southwest,2007.94500,Not Eligibble
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

## 7.Lambda

Anonymous function/nameless function

In [30]:
insurance_data["Eligible Criteria_2"] = insurance_data["age"].apply(lambda x:1 if x>20 else 0)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligible Criteria,Eligible Criteria_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligibble,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligibble,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligibble,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligibble,0
1336,21,female,25.800,0,no,southwest,2007.94500,Not Eligibble,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

In [47]:
insurance_data["EC"] = insurance_data["age"].apply(lambda x:"Eligible" if x>20 else "Not Eligible")
insurance_data

,age,sex,bmi,children,smoker,region,charges,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

### Explore list comprehension 3 examples

### Explore Lambda function - map,filter,query

## 8. Del Keyword

In [48]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [49]:
del insurance_data["EC"]
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]